/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReturnsPolicyRouteImport } from './routes/returns-policy'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as ProductSkuRouteImport } from './routes/product.$sku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsPolicyRoute = ReturnsPolicyRouteImport.update({
  id: '/returns-policy',
  path: '/returns-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSkuRoute = ProductSkuRouteImport.update({
  id: '/product/$sku',
  path: '/product/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$sku': typeof ProductSkuRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$sku': typeof ProductSkuRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$sku': typeof ProductSkuRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy-policy'
    | '/returns-policy'
    | '/shipping-policy'
    | '/shop'
    | '/terms'
    | '/account/addresses'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/products'
    | '/brand/$slug'
    | '/order/$orderNumber'
    | '/product/$sku'
    | '/account/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy-policy'
    | '/returns-policy'
    | '/shipping-policy'
    | '/shop'
    | '/terms'
    | '/account/addresses'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/products'
    | '/brand/$slug'
    | '/order/$orderNumber'
    | '/product/$sku'
    | '/account'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy-policy'
    | '/returns-policy'
    | '/shipping-policy'
    | '/shop'
    | '/terms'
    | '/account/addresses'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/products'
    | '/brand/$slug'
    | '/order/$orderNumber'
    | '/product/$sku'
    | '/account/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnsPolicyRoute: typeof ReturnsPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  BrandSlugRoute: typeof BrandSlugRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  ProductSkuRoute: typeof ProductSkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-policy': {
      id: '/returns-policy'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof ReturnsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$sku': {
      id: '/product/$sku'
      path: '/product/$sku'
      fullPath: '/product/$sku'
      preLoaderRoute: typeof ProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCouponsRoute: AdminCouponsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnsPolicyRoute: ReturnsPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  BrandSlugRoute: BrandSlugRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  ProductSkuRoute: ProductSkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
